version: "3"

networks:
  poa:
    driver: bridge

services:
  database:
    image: postgres:latest
    ports:
    - 5433:5432
    env_file:
    - ".env"
    volumes:
    - "./db_local/:/var/lib/postgresql/data/"
    env_file:
      - .env
    networks:
    - poa

  app:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    ports:
      - 3000:80
    volumes:
      - .:/app
    networks:
    - poa
